#pragma once

#include <Arduino.h>

#define CONFIG_PATH "/audio-spy/config.json"
#define CONFIG_TMP_PATH "/audio-spy/config.json.tmp"  // written first, then renamed
#define CONFIG_BAD_PATH "/audio-spy/config.json.bad"  // an unreadable config, kept for the user

// NTP time sync
#define NTP_SERVER "pool.ntp.org"
// POSIX time zone rule, including when DST starts/ends (this one: Central
// Europe), so daylight saving switches by itself.
#define TZ_INFO "CET-1CEST,M3.5.0,M10.5.0/3"

// Network name: the web UI is reachable at http://audio-spy.local (mDNS),
// and the router sees this as the device's DHCP hostname.
#define HOSTNAME "audio-spy"

struct Config {
    // Normalized RMS (0.0-1.0), compared against each second's RMS. Only the
    // first-boot default; normally set from the web UI's threshold slider.
    float threshold = 0.0015f;
    bool stealthMode = false;
    String webPassword = "cardputer";
    // Random key the web UI's login cookie is derived from (with
    // webPassword); generated by the web server once WiFi is up, see
    // web_server.cpp. Kept on the SD card (not in flash), so a firmware
    // update doesn't log everyone out; changing it or the password does.
    String sessionKey;
};

// Loads config from CONFIG_PATH, creating the file with defaults if it
// doesn't exist yet. Returns the loaded (or newly-created default) config.
Config configLoad();

// Persists the given config to CONFIG_PATH. Written to CONFIG_TMP_PATH and
// renamed over it, so a power cut never leaves a half-written file (which
// would silently reset the web password to the default on the next boot).
bool configSave(const Config& cfg);
